import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { FaCopy, FaTimes } from 'react-icons/fa';

// ✅ Correct API endpoint for ngrok + Flask
const GENERATION_API_URL = 'https://nonspherical-misfeatured-crissy.ngrok-free.dev/generate';

const AiCodeGenerator = ({ isOpen, onClose }) => {
    const [prompt, setPrompt] = useState('');
    const [generatedCode, setGeneratedCode] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            toast.error('Please enter a prompt.');
            return;
        }

        setIsLoading(true);
        setGeneratedCode('');

        try {
            const payload = { prompt };

            const response = await fetch(GENERATION_API_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(payload),
            });

            const result = await response.json();

            if (response.ok && result.code) {
                let text = result.code.trim();
                text = text.replace(/^```c\+\+\s*/, '').replace(/```\s*$/, '');
                setGeneratedCode(text);
                toast.success('Code generated by TinyLlama!');
            } else {
                const errorMessage = result.error || 'Unknown error occurred on the server.';
                toast.error(`Generation Failed: ${errorMessage}`);
                setGeneratedCode(`// Error from Server: ${errorMessage}`);
            }

        } catch (error) {
            console.error("Network or parsing error:", error);
            toast.error('Failed to connect to the code generation server.');
            setGeneratedCode(`// Network Error: Could not reach ${GENERATION_API_URL}`);
        } finally {
            setIsLoading(false);
        }
    };

    const handleCopy = () => {
        if (!generatedCode) return;
        navigator.clipboard.writeText(generatedCode)
            .then(() => toast.success('Code copied to clipboard!'))
            .catch(() => toast.error('Failed to copy code.'));
    };

    if (!isOpen) return null;

    return (
        <div className="ai-modal-overlay">
            <div className="ai-modal">
                <button className="ai-modal-close" onClick={onClose}><FaTimes /></button>
                <h2>Generate Arduino Code</h2>
                <textarea
                    className="ai-prompt-input"
                    placeholder="Enter your prompt (e.g., 'Blink an LED on pin 13 every second')"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    rows={4}
                />
                <button
                    className="btn ai-generate-btn"
                    onClick={handleGenerate}
                    disabled={isLoading}
                >
                    {isLoading ? 'Generating...' : 'Generate Code'}
                </button>
                {generatedCode && (
                    <div className="ai-output-area">
                        <h4>Generated Code:</h4>
                        <pre className="ai-output-box">{generatedCode}</pre>
                        <button className="btn ai-copy-btn" onClick={handleCopy}>
                            <FaCopy /> Copy Code
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AiCodeGenerator;